<a href="https://colab.research.google.com/github/BrenoMarinho/Estrutura-de-Dados---ANO-2024/blob/main/Circuitos_Formula1_A1_Breno_CPP_D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Atividade Avaliativa A1 - 5,0pts

 - Nome: Breno Silva Marinho

 - RGM: 1434318755

 - Disciplina: Estrutura de Dados

 - Tema: Top 10 circuitos de Fórmula 1 que mais receberam provas

 - Curiosidade: Com a Fórmula 1 estabelecendo um novo recorde de corridas no calendário da temporada, alcançando um total de 24 GPs (Grandes Prêmios) em 2024, o esporte celebra mais um marco significativo em sua história.
                Ao longo de 74 temporadas completas e sua atividade desde 1950, a categoria máxima do automobilismo acumula agora mais de 1.100 corridas disputadas.
                Esse fascinante percurso levou a Fórmula 1 a explorar aproximadamente 35 países e 77 circuitos ao redor do globo, demonstrando seu alcance global e seu papel vital no mundo do esporte a motor.

'''

In [ ]:
import pandas as pd #--> Importação da biblioteca pandas

# -- Criação de listas com os dados informados

CircuitName = ['Monza', 'Mônaco', 'Silverstone', 'Spa-Francorchamps', 'Gilles Villeneuve', 'Nurburgring', 'Interlagos', 'Hockenheimring', 'Suzuka', 'Zandvoort']
#-> Nome do circuito

TotalRuns = ['73', '69', '58', '56', '42', '41', '40', '37', '34', '33']
#-> Total de corridas

Location= ['Itália', 'Mônaco', 'Inglaterra', 'Bélgica', 'Canadá', 'Alemanha', 'Brasil', 'Hockenheimring', 'Japão', 'Holanda' ]
#-> Onde está localizada

TotalCurves = ['11', '19', '18', '19', '14', '16', '15', '15', '18', '14']
#-> Total de curvas da pista

WinningPilot = ['Michael Schumacher', 'Ayrton Senna', 'Lewis Hamilton', 'Michael Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Michael Schumacher', 'Lewis Hamilton']
#--> Piloto que mais ganhou no circuito

TrackSize = ['5,793 km', '3,337 km', '5,891 km', '7 km', '4,361 km', '5,148 km', '4,309 km', '3,629 km', '5,807 km', '4,3 km']
#-> Cumprimento da pista

Opening = ['1922', '1950', '1948', '1979', '1978', '1927','1940', '1932', '1962', '1948']
#-> Ano de inauguração do circuito

#Criação de um dicionário com as listas informadas
dados_circuitos= {
    'Nome do circuito': CircuitName,
    'Total de corridas': TotalRuns,
    'Localização': Location,
    'Total de Curvas': TotalCurves,
    'Piloto com mais vitória': WinningPilot,
    'Tamanho da pista': TrackSize,
    'Data de inauguração': Opening,

}

#Criação de um DataFrame com o dicionário
circuitos = pd.DataFrame(dados_circuitos)

> 1. Usando a biblioteca Pandas foi-se criado um DataFrame sobre os circuitos mais relevantes da Fórmula 1.
2. Utilizando listas para armazenar os dados coletados e, com elas, foi feito um dicionário, que foi utilizado para a criação do DataFrame e sua variável.

### 1 - Apresente em tela (output) toda a base de dados.

In [ ]:
print("1) Apresente em tela (output) toda a base de dados.")
#Utilizo o comando display para apresentar todos os dados do DataFrame.
display(circuitos)
print()

1) Apresente em tela (output) toda a base de dados.

,Nome do circuito,Total de corridas,Localização,Total de Curvas,Piloto com mais vitória,Tamanho da pista,Data de inauguração
0,Monza,73,Itália,11,Michael Schumacher,"5,793 km",1922
1,Mônaco,69,Mônaco,19,Ayrton Senna,"3,337 km",1950
2,Silverstone,58,Inglaterra,18,Lewis Hamilton,"5,891 km",1948
3,Spa-Francorchamps,56,Bélgica,19,Michael Schumacher,7 km,1979
4,Gilles Villeneuve,42,Canadá,14,Michael Schumacher,"4,361 km",1978
5,Nurburgring,41,Alemanha,16,Michael Schumacher,"5,148 km",1927
6,Interlagos,40,Brasil,15,Michael Schumacher,"4,309 km",1940
7,Hockenheimring,37,Hockenheimring,15,Michael Schumacher,"3,629 km",1932
8,Suzuka,34,Japão,18,Michael Schumacher,"5,807 km",1962
9,Zandvoort,33,Holanda,14,Lewis Hamilton,"4,3 km",1948


---

### Explicando o Código 🚨

> 1. Criação de um Dicionário:
Um dicionário data é criado com chaves representando as colunas e valores como listas de dados para cada coluna.


* Nome do circuito: Descreve o nome dado ao circuito.
* Total de corridas: Lista o total de corridas no circuito.
* Localização: Lista a cidade, cidade ou estado que ocrreu o circuito.
* Total de Curvas: Lista a total de curvas do circuito.
* Piloto com mais vitória: Lista o nome do piloto com mais número de vitórias.
* Tamanho da pista:Lista do tamanho em quilômetro.
* Data de inauguração: Lista o ano em que o circuito doi inaugurado.

> 2. Criação do DataFrame


* O dicionário circuito é passado para o construtor  ```pd.DataFrame() ``` para criar um DataFrame chamado  ```dados_circuito ```.

In [ ]:
circuitos = pd.DataFrame(dados_circuitos)

> 3. Exibição do DataFrame

* O método  ```display() ``` é utilizado para exibir o DataFrame circuito.

In [ ]:
display(circuitos)

### 2 - Apresente o tamanho do seu dataframe (quantas linhas x colunas).

In [ ]:
print("2) Apresente o tamanho do seu dataframe (quantas linhas x colunas).")
#O comando shape mostrará as dimenções do DataFrame (Linhas e Colunas).
num_linhas, num_colunas = circuitos.shape
print(f"O DataFrame tem {num_linhas} linhas e {num_colunas} colunas.")
print()

2) Apresente o tamanho do seu dataframe (quantas linhas x colunas).
O DataFrame tem 10 linhas e 7 colunas.

---

### Explicando o Código 🚨

1. Apresentar o Tamanho do DataFrame:


* ```dataframe.shape```: Retorna uma tupla que contém o número de linhas e colunas do DataFrame. No formato ```(n_linhas, n_colunas)```.
* ```num_linhas, num_colunas = dataframe.shape```: Desempacota a tupla em duas variáveis: ```num_linhas``` e ```num_colunas```.
* ```print(f"O DataFrame tem {num_linhas} linhas e {num_colunas} colunas.")```: Imprime o tamanho do DataFrame no formato "O DataFrame tem X linhas e Y colunas".

### 3 - Acesse a linha (x) e apresente em tela todas as características do item.

In [ ]:
print("3) Acesse a linha (x) e apresente em tela todas as características do item.")
#O comando iloc irá alocar apenas a linha e coluna especificada, neste caso, a primeira linha.
linha_x = 3
print(f"Características da linha {linha_x}:")
print()
print(circuitos.iloc[linha_x])

3) Acesse a linha (x) e apresente em tela todas as características do item.
Características da linha 3:

Nome do circuito            Spa-Francorchamps
Total de corridas                          56
Localização                           Bélgica
Total de Curvas                            19
Piloto com mais vitória    Michael Schumacher
Tamanho da pista                         7 km
Data de inauguração                      1979
Name: 3, dtype: object

---

### Explicando o Código 🚨

* Acessar a linha específica (x) e exibir todas as suas características:

* ```linha_x = 3```: Define o índice da linha que queremos acessar, neste caso, a linha 3.
* ```print(f"Características da linha {linha_x}:")```: Imprime uma mensagem indicando qual linha estamos acessando.
* ```dataframe.iloc[linha_x]```: Acessa a linha de índice ```3``` do DataFrame ```dataframe``` utilizando o método ```iloc```. O método ```iloc``` permite acessar linhas e colunas pelo índice (inteiro) ao invés de rótulos (nomes).
* ```print(dataframe.iloc[linha_x])```: Exibe todas as características (valores de todas as colunas) da linha de índice ```3```.

### 4 - Verifique se o DataFrame está vazio.

In [ ]:
print("4) Verifique se o dataframe está vazio.")
#Utilizando Do-While: imprimir na tela "o DataFrame está vazio" ou "O DataFrame não está vazio"
while circuitos.empty:
  print("O DataFrame está vazio!")
  break
else:
  print("O DataFrame não está vazio!!")

4) Verifique se o dataframe está vazio.
O DataFrame não está vazio!!

In [ ]:
#Usando circuitos.empty: O comando empty irá retornar na tela se o DataFrame está vazio ou não utilizando true ou false
print("4) Verifique se o dataframe está vazio.")
print(circuitos.empty)
print()

4) Verifique se o dataframe está vazio.
False

---

### Explicando o Código 🚨

> 1. Definindo o DataFrame Vazio Antes de Usá-lo no Loop:

* ```while circuitos.empty:```: Inicia um loop while, onde a condição de parada é que o DataFrame ```empty_circuitos``` esteja vazio.
* ```print(f"O DataFrame está vazio!")```: Se o DataFrame estiver vazio, imprime a mensagem "O DataFrame está vazio!".
* ```break```: Encerra o loop após imprimir a mensagem.
* ```else:```: Parte do loop ```while``` que é executada se a condição do loop não for atendida (ou seja, se o DataFrame não estiver vazio).
* ```print("O DataFrame não está vazio!!")```: Imprime a mensagem "O DataFrame possui itens." se o DataFrame não estiver vazio.

> 2.   Usando circuitos.empty

* Atravéz do método ```circuitos.empty```, ele retornará na tela se o DataFrame está vazio ou não (usando True ou False para determinar sua resposta)

### 5 - Apresente em tela os 5 primeiros registros da base de dados.

In [ ]:
print("5) Apresente em tela os 5 primeiros registros da base de dados.")
#O comando head irá retonar a quantidade de linhas pedidas com o uso de (), neste caso, as 5 primeiras linahs serão retornadas.
print(circuitos.head(5))
print()

5) Apresente em tela os 5 primeiros registros da base de dados.
    Nome do circuito Total de corridas Localização Total de Curvas  \
0              Monza                73      Itália              11
1             Mônaco                69      Mônaco              19
2        Silverstone                58  Inglaterra              18
3  Spa-Francorchamps                56     Bélgica              19
4  Gilles Villeneuve                42      Canadá              14

  Piloto com mais vitória Tamanho da pista Data de inauguração
0      Michael Schumacher         5,793 km                1922
1            Ayrton Senna         3,337 km                1950
2          Lewis Hamilton         5,891 km                1948
3      Michael Schumacher             7 km                1979
4      Michael Schumacher         4,361 km                1978

---

### Explicando o Código 🚨

> 1. Exibir os 5 Primeiros Registros do DataFrame:

Neste trecho, estamos exibindo os 5 primeiros registros (linhas) do DataFrame dataframe utilizando o método head().

* ```print()```: Exibe o resultado de ```circuitos.head(5)``` de forma mais amigável e interativa.

In [ ]:
print(circuitos.head(5))

### 6 - Exclua um item (linha) de sua base de dados.

In [ ]:
print("6) Exclua um item (linha) de sua base de dados.")
#O comando drop irá excluir uma linha (especificada entre ()) do DataFrame.
circuitos = circuitos.drop(2)
print("\nDataFrame após a remoção da linha com índice 2:")
print(circuitos)
print()

6) Exclua um item (linha) de sua base de dados.

DataFrame após a remoção da linha com índice 2:
    Nome do circuito Total de corridas     Localização Total de Curvas  \
0              Monza                73          Itália              11
1             Mônaco                69          Mônaco              19
3  Spa-Francorchamps                56         Bélgica              19
4  Gilles Villeneuve                42          Canadá              14
5        Nurburgring                41        Alemanha              16
6         Interlagos                40          Brasil              15
7     Hockenheimring                37  Hockenheimring              15
8             Suzuka                34           Japão              18
9          Zandvoort                33         Holanda              14

  Piloto com mais vitória Tamanho da pista Data de inauguração
0      Michael Schumacher         5,793 km                1922
1            Ayrton Senna         3,337 km                1950
3      Michael Schumacher             7 km                1979
4      Michael Schumacher         4,361 km                1978
5      Michael Schumacher         5,148 km                1927
6      Michael Schumacher         4,309 km                1940
7      Michael Schumacher         3,629 km                1932
8      Michael Schumacher         5,807 km                1962
9          Lewis Hamilton           4,3 km                1948


---

### Explicação do Código 🚨

1. Remover a Linha com Índice 2:

Neste trecho, estamos removendo a linha com índice 2 (correspondente ao circuito de Mônaco) do DataFrame ```circuitos``` utilizando o método ```drop()```.
* ```circuitos = circuitos.drop(2)```: Retorna um novo DataFrame com a linha especificada removida.

### 7 - Adicione um item (linha) na sua base de dados.

In [ ]:
print("7) Adicione um item (linha) na sua base de dados.")
#Nessa fase dicionei uma nova linha no DataFrame com a ajuda do dicionario.
#Obs.: Foi um circuito aleatório
novo_circuito = {
    'Nome do circuito': 'Catalunha',
    'Total de corridas': '29',
    'Localização': 'Espanha',
    'Total de Curvas': '14',
    'Piloto com mais vitória': 'Valentino Rossi',
    'Tamanho da pista': '4,657 km',
    'Data de inauguração': '1991',
    }
circuitos = pd.concat([circuitos, pd.DataFrame(novo_circuito, index=[5])],ignore_index=True)
print(circuitos)
print()

7) Adicione um item (linha) na sua base de dados.
    Nome do circuito Total de corridas     Localização Total de Curvas  \
0              Monza                73          Itália              11
1             Mônaco                69          Mônaco              19
2  Spa-Francorchamps                56         Bélgica              19
3  Gilles Villeneuve                42          Canadá              14
4        Nurburgring                41        Alemanha              16
5         Interlagos                40          Brasil              15
6     Hockenheimring                37  Hockenheimring              15
7             Suzuka                34           Japão              18
8          Zandvoort                33         Holanda              14
9          Catalunha                29         Espanha              14

  Piloto com mais vitória Tamanho da pista Data de inauguração
0      Michael Schumacher         5,793 km                1922
1            Ayrton Senna         3,337 km                1950
2      Michael Schumacher             7 km                1979
3      Michael Schumacher         4,361 km                1978
4      Michael Schumacher         5,148 km                1927
5      Michael Schumacher         4,309 km                1940
6      Michael Schumacher         3,629 km                1932
7      Michael Schumacher         5,807 km                1962
8          Lewis Hamilton           4,3 km                1948
9         Valentino Rossi         4,657 km                1991

---

### Explicação do Código 🚨

> 1. Novo Item a ser Adicionado:

* Este trecho define um novo circuito que será adicionado ao DataFrame. O item é representado como um dicionário com chaves correspondentes aos nomes das colunas do DataFrame, citado novamente abaixo:

In [ ]:
novo_circuito = {
    'Nome do circuito': 'Catalunha',
    'Total de corridas': '29',
    'Localização': 'Espanha',
    'Total de Curvas': '14',
    'Piloto com mais vitória': 'Valentino Rossi',
    'Tamanho da pista': '4,657 km',
    'Data de inauguração': '1991',
    }

> 2. Adicionar o Novo Item ao DataFrame Usando `pd.concat`:

* Neste trecho, estamos adicionando um novo circuito `novo_circuito` ao final do DataFrame `circuitos` utilizando a função `pd.concat()`. O parâmetro `ignore_index=True` garante que os índices das linhas sejam redefinidos após a concatenação, para evitar índices duplicados.

In [ ]:
circuitos = pd.concat([circuitos, pd.DataFrame(novo_circuito, index=[5])],ignore_index=True)

### 8 - Transponha a coluna para a linha em sua base de dados.

In [ ]:
print("8) Transponha a coluna para a linha em sua base de dados.")
# Transpor uma coluna específica, por exemplo, a coluna 'Localização'
coluna_localizacao_transposta = circuitos['Localização'].to_frame().T

# Exibir a coluna transposta
print()
print("\nColuna 'Localização' transposta para linha:")
display(coluna_localizacao_transposta)

# Transpor todo o DataFrame e exibi-lo
print("\nDataFrame transposto:")
circuitos_transposto = circuitos.T
circuitos_transposto

8) Transponha a coluna para a linha em sua base de dados.


Coluna 'Localização' transposta para linha:

,0,1,2,3,4,5,6,7,8,9
Localização,Itália,Mônaco,Bélgica,Canadá,Alemanha,Brasil,Hockenheimring,Japão,Holanda,Espanha

DataFrame transposto:

,0,1,2,3,4,5,6,7,8,9
Nome do circuito,Monza,Mônaco,Spa-Francorchamps,Gilles Villeneuve,Nurburgring,Interlagos,Hockenheimring,Suzuka,Zandvoort,Catalunha
Total de corridas,73,69,56,42,41,40,37,34,33,29
Localização,Itália,Mônaco,Bélgica,Canadá,Alemanha,Brasil,Hockenheimring,Japão,Holanda,Espanha
Total de Curvas,11,19,19,14,16,15,15,18,14,14
Piloto com mais vitória,Michael Schumacher,Ayrton Senna,Michael Schumacher,Michael Schumacher,Michael Schumacher,Michael Schumacher,Michael Schumacher,Michael Schumacher,Lewis Hamilton,Valentino Rossi
Tamanho da pista,"5,793 km","3,337 km",7 km,"4,361 km","5,148 km","4,309 km","3,629 km","5,807 km","4,3 km","4,657 km"
Data de inauguração,1922,1950,1979,1978,1927,1940,1932,1962,1948,1991


---

### Explicando o Código 🚨

> 1. Transpor uma Coluna Específica (Exemplo: Coluna 'Localização'):

* Aqui, estamos transpondo a coluna específica `'localização'` do DataFrame `circuitos`. Primeiro, selecionamos essa coluna utilizando `circuitos['Localização']`, depois convertemos em um DataFrame usando `to_frame()`, e finalmente aplicamos a transposição usando `.T`.

In [ ]:
coluna_localizacao_transposta = circuitos['Localização'].to_frame().T

> 2. Transpor Todo o DataFrame:

* Caso solictado, é possível transpor todo o DataFrame `circuitos` utilizando o método `.T`. Isso trocará as linhas pelas colunas e vice-versa.

In [ ]:
circuitos_transposto = circuitos.T

### 9 - Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados.

In [ ]:
print("9) Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados.")
#Utilizando uma variável do comando iloc, definindo as colunas que queremos alocar e apresentando-as em tela.
print(circuitos.loc[:, ['Nome do circuito', 'Total de corridas']])
print()

9) Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados.
    Nome do circuito Total de corridas
0              Monza                73
1             Mônaco                69
2  Spa-Francorchamps                56
3  Gilles Villeneuve                42
4        Nurburgring                41
5         Interlagos                40
6     Hockenheimring                37
7             Suzuka                34
8          Zandvoort                33
9          Catalunha                29


---

### Explicando o Código 🚨

> 1. Selecionar e Exibir Apenas a 1ª e 2ª Coluna:

* Aqui, estamos selecionando apenas as colunas `'Nome do circuito'` e `'Total de corridas'` do DataFrame `circuito` utilizando a notação de lista dupla `[:, ['Nome do circuito', 'Total de corridas']]` a partir da função `loc`, que é uma variação da função `iloc`.

In [ ]:
print(circuitos.loc[:, ['Nome do circuito', 'Total de corridas']])

### 10 - Informe como foi desenvolvido o Projeto

Neste projeto, concentrado na criação e manipulação de um DataFrame usando a biblioteca Pandas em Python. O tema escolhido foi `Os 10 circuitos de Fórmula 1 que mais receberam provas`. Foi coletado dados relevantes, incluindo informações sobre o nome do circuito, o total de corridas realizadas, a localização geográfica, o número de curvas do circuito, o piloto com o maior número de vitórias, o tamanho da pista e o ano de inauguração.

> Etapas do Projeto:
1. Coleta de Dados:
* Foi reunido informações sobre os circuitos, como nome, localização, número de corridas, curvas, tamanho da pista e piloto com mais vitórias. Esses dados foram organizados em listas.
2. Agrupamento em um Dicionário:
* Criado um dicionário em que cada chave representa uma característica específica de um circuito de Fórmula 1.
* As listas de dados foram agrupadas nesse dicionário.
3. Criação do DataFrame:
* Foi utilizado o dicionário para criar um DataFrame, uma estrutura de dados bidimensional com rótulos para linhas e colunas, fornecida pela biblioteca Pandas.
4. Operações no DataFrame:
* Aplicando várias operações ao DataFrame para responder às perguntas propostas:
** shape: Para obter o tamanho do DataFrame.
** iloc: Acesso a linhas específicas.
** empty: Verificação se o DataFrame estava vazio.
** head: Apresentação dos primeiros registros.
** drop: Exclução de uma linha.
5. Transposição do DataFrame:
* Utilizando o método .T para transpor o DataFrame, trocando linhas por colunas.
Acesso às colunas específicas com .loc.
6. Explicação e Análise:
* Após a explicação de cada etapa, aplicando corretamente os comandos do Pandas.
Para apresentar uma maior volumetria, foram feitas pesquisas em sites adicionais e testes práticos para garantir a precisão dos resultados.

Ademais, o tema escolhido foi com base em vivências e descobertas, pois recentemente acomapnhar as transmissões dos GPs (Grandes Prêmios) se tornou algo agradável, um bom passa tempo aos final de semana e fofocar sobre a assunto no decorrer dos dias e como forma de estudo/aprendizagem e aprofudamento para acompanhar o esporte, desenvolvi esse Data Frame. Ao final, este projeto proporcionou uma compreensão sólida da manipulação de dados com Pandas. Além disso, demonstrou como trabalhar eficientemente com informações relacionadas aos circuitos de Fórmula 1.

...

# FONTES E LINKS:

 - https://gulfcombustiveis.com.br/blog/2024/04/22/os-10-circuitos-que-mais-receberam-corridas-da-formula-1/


 - https://www.band.uol.com.br/esportes/automobilismo/formula-1/noticias/quais-sao-os-10-maiores-circuitos-da-historia-da-formula-1-confira-a-lista-16458403

 > Todos os dados coletados foram retirados de sites, o primeiro se referente a Gulf, sendo uma pioneira mundial quando se trata de postos de combustíveis, vinculada a Fórmula 1 desde 1936 e uma das patrocinados das marcas dos carros. O outro site é a Band, a principal transmissora das corridas ao vivo no Brasil tanto em conteúdo na TV ou em plataformas digitais.

 - Curso Intensivo de Python: Uma introdução prática e baseada em projetos à programação, Eric Matthes:
Disponívem em Português: https://edisciplinas.usp.br/pluginfile.php/6585696/mod_resource/content/1/Eric%20Matthes%20-%20Curso%20Intensivo%20de%20Python-Novatec%20%282016%29.pdf

 > As informações sobre a criação do DataFrame foram tiradas do conteúdo mestrado em sala de aula junto a Professora Kadidja, vinculada à UDF - Universidade do Distrito Federal, ministrando a disciplina de Estrutura de Dados, em que foi possível construir uma consistente base para a conclusão. E ao livro do "Curso Intensivo de Python: Uma introdução prática e baseada em projetos à programação" do autor Eric Matthes, publicado em 17 de maio de 2016.

 - https://pandas.pydata.org/docs/

 > O site pandas é a documentação oficial da biblioteca pandas para Python.


 ...